# TCL File Generated by Component Editor 18.1
# Sat Mar 21 13:26:17 NZDT 2020
# DO NOT MODIFY


# 
# convolution "convolution" v1.0
#  2020.03.21.13:26:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module convolution
# 
set_module_property DESCRIPTION ""
set_module_property NAME convolution
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Custom_IP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME convolution
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL convolution
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file convolution.sv SYSTEM_VERILOG PATH convolution.sv TOP_LEVEL_FILE
add_fileset_file convolution_calc.sv SYSTEM_VERILOG PATH convolution_calc.sv


# 
# parameters
# 
add_parameter XRES INTEGER 224
set_parameter_property XRES DEFAULT_VALUE 224
set_parameter_property XRES DISPLAY_NAME XRES
set_parameter_property XRES TYPE INTEGER
set_parameter_property XRES UNITS None
set_parameter_property XRES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XRES HDL_PARAMETER true
add_parameter YRES INTEGER 224
set_parameter_property YRES DEFAULT_VALUE 224
set_parameter_property YRES DISPLAY_NAME YRES
set_parameter_property YRES TYPE INTEGER
set_parameter_property YRES UNITS None
set_parameter_property YRES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property YRES HDL_PARAMETER true
add_parameter PADDING INTEGER 1
set_parameter_property PADDING DEFAULT_VALUE 1
set_parameter_property PADDING DISPLAY_NAME PADDING
set_parameter_property PADDING TYPE INTEGER
set_parameter_property PADDING UNITS None
set_parameter_property PADDING ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PADDING HDL_PARAMETER true


# 
# display items
# 


# 
# connection point master_1
# 
add_interface master_1 avalon start
set_interface_property master_1 addressUnits SYMBOLS
set_interface_property master_1 associatedClock clock
set_interface_property master_1 associatedReset clock_sreset
set_interface_property master_1 bitsPerSymbol 8
set_interface_property master_1 burstOnBurstBoundariesOnly false
set_interface_property master_1 burstcountUnits WORDS
set_interface_property master_1 doStreamReads false
set_interface_property master_1 doStreamWrites false
set_interface_property master_1 holdTime 0
set_interface_property master_1 linewrapBursts false
set_interface_property master_1 maximumPendingReadTransactions 0
set_interface_property master_1 maximumPendingWriteTransactions 0
set_interface_property master_1 readLatency 0
set_interface_property master_1 readWaitTime 1
set_interface_property master_1 setupTime 0
set_interface_property master_1 timingUnits Cycles
set_interface_property master_1 writeWaitTime 0
set_interface_property master_1 ENABLED true
set_interface_property master_1 EXPORT_OF ""
set_interface_property master_1 PORT_NAME_MAP ""
set_interface_property master_1 CMSIS_SVD_VARIABLES ""
set_interface_property master_1 SVD_ADDRESS_GROUP ""

add_interface_port master_1 m1_address address Output 32
add_interface_port master_1 m1_readdata readdata Input 16
add_interface_port master_1 m1_read read Output 1
add_interface_port master_1 m1_waitrequest waitrequest Input 1


# 
# connection point master_2
# 
add_interface master_2 avalon start
set_interface_property master_2 addressUnits SYMBOLS
set_interface_property master_2 associatedClock clock
set_interface_property master_2 associatedReset clock_sreset
set_interface_property master_2 bitsPerSymbol 8
set_interface_property master_2 burstOnBurstBoundariesOnly false
set_interface_property master_2 burstcountUnits WORDS
set_interface_property master_2 doStreamReads false
set_interface_property master_2 doStreamWrites false
set_interface_property master_2 holdTime 0
set_interface_property master_2 linewrapBursts false
set_interface_property master_2 maximumPendingReadTransactions 0
set_interface_property master_2 maximumPendingWriteTransactions 0
set_interface_property master_2 readLatency 0
set_interface_property master_2 readWaitTime 1
set_interface_property master_2 setupTime 0
set_interface_property master_2 timingUnits Cycles
set_interface_property master_2 writeWaitTime 0
set_interface_property master_2 ENABLED true
set_interface_property master_2 EXPORT_OF ""
set_interface_property master_2 PORT_NAME_MAP ""
set_interface_property master_2 CMSIS_SVD_VARIABLES ""
set_interface_property master_2 SVD_ADDRESS_GROUP ""

add_interface_port master_2 m2_address address Output 32
add_interface_port master_2 m2_writedata writedata Output 16
add_interface_port master_2 m2_write write Output 1
add_interface_port master_2 m2_waitrequest waitrequest Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point clock_sreset
# 
add_interface clock_sreset reset end
set_interface_property clock_sreset associatedClock clock
set_interface_property clock_sreset synchronousEdges DEASSERT
set_interface_property clock_sreset ENABLED true
set_interface_property clock_sreset EXPORT_OF ""
set_interface_property clock_sreset PORT_NAME_MAP ""
set_interface_property clock_sreset CMSIS_SVD_VARIABLES ""
set_interface_property clock_sreset SVD_ADDRESS_GROUP ""

add_interface_port clock_sreset clock_sreset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset clock_sreset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 4
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_writedata writedata Input 32
add_interface_port slave s_read read Input 1
add_interface_port slave s_write write Input 1
add_interface_port slave s_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0

