# TCL File Generated by Component Editor 13.0
# Sat Mar 28 17:38:52 NZDT 2020
# DO NOT MODIFY


# 
# i2c_master "i2c_master" v1.0
#  2020.03.28.17:38:52
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module i2c_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2c_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CustomIP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME i2c_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_master.sv SYSTEM_VERILOG PATH i2c_master.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter I2C_SPEED INTEGER 400000
set_parameter_property I2C_SPEED DEFAULT_VALUE 400000
set_parameter_property I2C_SPEED DISPLAY_NAME I2C_SPEED
set_parameter_property I2C_SPEED TYPE INTEGER
set_parameter_property I2C_SPEED UNITS None
set_parameter_property I2C_SPEED HDL_PARAMETER true
add_parameter CLOCK_HZ INTEGER 50000000
set_parameter_property CLOCK_HZ DEFAULT_VALUE 50000000
set_parameter_property CLOCK_HZ DISPLAY_NAME CLOCK_HZ
set_parameter_property CLOCK_HZ TYPE INTEGER
set_parameter_property CLOCK_HZ UNITS None
set_parameter_property CLOCK_HZ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset clock_sreset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave address address Input 4
add_interface_port slave readdata readdata Output 32
add_interface_port slave writedata writedata Input 32
add_interface_port slave read read Input 1
add_interface_port slave write write Input 1
add_interface_port slave waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point clock_sreset
# 
add_interface clock_sreset reset end
set_interface_property clock_sreset associatedClock clock
set_interface_property clock_sreset synchronousEdges DEASSERT
set_interface_property clock_sreset ENABLED true
set_interface_property clock_sreset EXPORT_OF ""
set_interface_property clock_sreset PORT_NAME_MAP ""
set_interface_property clock_sreset SVD_ADDRESS_GROUP ""

add_interface_port clock_sreset clock_sreset reset Input 1


# 
# connection point i2c
# 
add_interface i2c conduit end
set_interface_property i2c associatedClock clock
set_interface_property i2c associatedReset clock_sreset
set_interface_property i2c ENABLED true
set_interface_property i2c EXPORT_OF ""
set_interface_property i2c PORT_NAME_MAP ""
set_interface_property i2c SVD_ADDRESS_GROUP ""

add_interface_port i2c sda export Bidir 1
add_interface_port i2c scl export Bidir 1

