// megafunction wizard: %ALTINT_OSC%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTINT_OSC 

// ============================================================
// File Name: oscillator.v
// Megafunction Name(s):
// 			ALTINT_OSC
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 18.1.0 Build 625 09/12/2018 SJ Standard Edition
// ************************************************************


//Copyright (C) 2018  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.


//altint_osc CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone IV E" clkout oscena
//VERSION_BEGIN 18.1 cbx_altint_osc 2018:09:12:13:04:24:SJ cbx_arriav 2018:09:12:13:04:23:SJ cbx_cycloneii 2018:09:12:13:04:24:SJ cbx_lpm_add_sub 2018:09:12:13:04:24:SJ cbx_lpm_compare 2018:09:12:13:04:24:SJ cbx_lpm_counter 2018:09:12:13:04:24:SJ cbx_lpm_decode 2018:09:12:13:04:24:SJ cbx_mgl 2018:09:12:13:10:36:SJ cbx_nadder 2018:09:12:13:04:24:SJ cbx_nightfury 2018:09:12:13:04:24:SJ cbx_stratix 2018:09:12:13:04:24:SJ cbx_stratixii 2018:09:12:13:04:24:SJ cbx_stratixiii 2018:09:12:13:04:24:SJ cbx_stratixv 2018:09:12:13:04:24:SJ cbx_tgx 2018:09:12:13:04:24:SJ cbx_zippleback 2018:09:12:13:04:24:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = cycloneive_oscillator 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  oscillator_altint_osc_i57
	( 
	clkout,
	oscena) ;
	output   clkout;
	input   oscena;

	wire  wire_sd1_clkout;

	cycloneive_oscillator   sd1
	( 
	.clkout(wire_sd1_clkout),
	.oscena(oscena));
	assign
		clkout = wire_sd1_clkout;
endmodule //oscillator_altint_osc_i57
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module oscillator (
	oscena,
	clkout);

	input	  oscena;
	output	  clkout;

	wire  sub_wire0;
	wire  clkout = sub_wire0;

	oscillator_altint_osc_i57	oscillator_altint_osc_i57_component (
				.oscena (oscena),
				.clkout (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: USED_PORT: clkout 0 0 0 0 OUTPUT NODEFVAL "clkout"
// Retrieval info: USED_PORT: oscena 0 0 0 0 INPUT NODEFVAL "oscena"
// Retrieval info: CONNECT: @oscena 0 0 0 0 oscena 0 0 0 0
// Retrieval info: CONNECT: clkout 0 0 0 0 @clkout 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL oscillator.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL oscillator.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL oscillator.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL oscillator.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL oscillator_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL oscillator_bb.v FALSE
