# TCL File Generated by Component Editor 18.1
# Mon Sep 07 11:03:35 NZST 2020
# DO NOT MODIFY


# 
# convolution "convolution" v1.0
#  2020.09.07.11:03:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module convolution
# 
set_module_property DESCRIPTION ""
set_module_property NAME convolution
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CustomIP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME convolution
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL convolution
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file convolution.sv SYSTEM_VERILOG PATH convolution.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter MAX_XRES INTEGER 256
set_parameter_property MAX_XRES DEFAULT_VALUE 256
set_parameter_property MAX_XRES DISPLAY_NAME MAX_XRES
set_parameter_property MAX_XRES TYPE INTEGER
set_parameter_property MAX_XRES UNITS None
set_parameter_property MAX_XRES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_XRES HDL_PARAMETER true
add_parameter XRES1 INTEGER 16
set_parameter_property XRES1 DEFAULT_VALUE 16
set_parameter_property XRES1 DISPLAY_NAME XRES1
set_parameter_property XRES1 TYPE INTEGER
set_parameter_property XRES1 UNITS None
set_parameter_property XRES1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XRES1 HDL_PARAMETER true
add_parameter XRES2 INTEGER 32
set_parameter_property XRES2 DEFAULT_VALUE 32
set_parameter_property XRES2 DISPLAY_NAME XRES2
set_parameter_property XRES2 TYPE INTEGER
set_parameter_property XRES2 UNITS None
set_parameter_property XRES2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XRES2 HDL_PARAMETER true
add_parameter XRES3 INTEGER 64
set_parameter_property XRES3 DEFAULT_VALUE 64
set_parameter_property XRES3 DISPLAY_NAME XRES3
set_parameter_property XRES3 TYPE INTEGER
set_parameter_property XRES3 UNITS None
set_parameter_property XRES3 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XRES3 HDL_PARAMETER true
add_parameter XRES4 INTEGER 128
set_parameter_property XRES4 DEFAULT_VALUE 128
set_parameter_property XRES4 DISPLAY_NAME XRES4
set_parameter_property XRES4 TYPE INTEGER
set_parameter_property XRES4 UNITS None
set_parameter_property XRES4 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XRES4 HDL_PARAMETER true
add_parameter XRES5 INTEGER 256
set_parameter_property XRES5 DEFAULT_VALUE 256
set_parameter_property XRES5 DISPLAY_NAME XRES5
set_parameter_property XRES5 TYPE INTEGER
set_parameter_property XRES5 UNITS None
set_parameter_property XRES5 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XRES5 HDL_PARAMETER true
add_parameter YRES1 INTEGER 16
set_parameter_property YRES1 DEFAULT_VALUE 16
set_parameter_property YRES1 DISPLAY_NAME YRES1
set_parameter_property YRES1 TYPE INTEGER
set_parameter_property YRES1 UNITS None
set_parameter_property YRES1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property YRES1 HDL_PARAMETER true
add_parameter YRES2 INTEGER 32
set_parameter_property YRES2 DEFAULT_VALUE 32
set_parameter_property YRES2 DISPLAY_NAME YRES2
set_parameter_property YRES2 TYPE INTEGER
set_parameter_property YRES2 UNITS None
set_parameter_property YRES2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property YRES2 HDL_PARAMETER true
add_parameter YRES3 INTEGER 64
set_parameter_property YRES3 DEFAULT_VALUE 64
set_parameter_property YRES3 DISPLAY_NAME YRES3
set_parameter_property YRES3 TYPE INTEGER
set_parameter_property YRES3 UNITS None
set_parameter_property YRES3 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property YRES3 HDL_PARAMETER true
add_parameter YRES4 INTEGER 128
set_parameter_property YRES4 DEFAULT_VALUE 128
set_parameter_property YRES4 DISPLAY_NAME YRES4
set_parameter_property YRES4 TYPE INTEGER
set_parameter_property YRES4 UNITS None
set_parameter_property YRES4 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property YRES4 HDL_PARAMETER true
add_parameter YRES5 INTEGER 256
set_parameter_property YRES5 DEFAULT_VALUE 256
set_parameter_property YRES5 DISPLAY_NAME YRES5
set_parameter_property YRES5 TYPE INTEGER
set_parameter_property YRES5 UNITS None
set_parameter_property YRES5 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property YRES5 HDL_PARAMETER true
add_parameter RESOLUTIONS INTEGER 5
set_parameter_property RESOLUTIONS DEFAULT_VALUE 5
set_parameter_property RESOLUTIONS DISPLAY_NAME RESOLUTIONS
set_parameter_property RESOLUTIONS TYPE INTEGER
set_parameter_property RESOLUTIONS UNITS None
set_parameter_property RESOLUTIONS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RESOLUTIONS HDL_PARAMETER true
add_parameter KX INTEGER 3
set_parameter_property KX DEFAULT_VALUE 3
set_parameter_property KX DISPLAY_NAME KX
set_parameter_property KX TYPE INTEGER
set_parameter_property KX UNITS None
set_parameter_property KX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property KX HDL_PARAMETER true
add_parameter KY INTEGER 3
set_parameter_property KY DEFAULT_VALUE 3
set_parameter_property KY DISPLAY_NAME KY
set_parameter_property KY TYPE INTEGER
set_parameter_property KY UNITS None
set_parameter_property KY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property KY HDL_PARAMETER true
add_parameter EXP INTEGER 8
set_parameter_property EXP DEFAULT_VALUE 8
set_parameter_property EXP DISPLAY_NAME EXP
set_parameter_property EXP TYPE INTEGER
set_parameter_property EXP UNITS None
set_parameter_property EXP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property EXP HDL_PARAMETER true
add_parameter MANT INTEGER 7
set_parameter_property MANT DEFAULT_VALUE 7
set_parameter_property MANT DISPLAY_NAME MANT
set_parameter_property MANT TYPE INTEGER
set_parameter_property MANT UNITS None
set_parameter_property MANT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MANT HDL_PARAMETER true
add_parameter WIDTHF INTEGER 16
set_parameter_property WIDTHF DEFAULT_VALUE 16
set_parameter_property WIDTHF DISPLAY_NAME WIDTHF
set_parameter_property WIDTHF TYPE INTEGER
set_parameter_property WIDTHF UNITS None
set_parameter_property WIDTHF HDL_PARAMETER true
add_parameter WIDTH INTEGER 16
set_parameter_property WIDTH DEFAULT_VALUE 16
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter WIDTHBE INTEGER 2
set_parameter_property WIDTHBE DEFAULT_VALUE 2
set_parameter_property WIDTHBE DISPLAY_NAME WIDTHBE
set_parameter_property WIDTHBE TYPE INTEGER
set_parameter_property WIDTHBE UNITS None
set_parameter_property WIDTHBE HDL_PARAMETER true
add_parameter WIDTHR INTEGER 5
set_parameter_property WIDTHR DEFAULT_VALUE 5
set_parameter_property WIDTHR DISPLAY_NAME WIDTHR
set_parameter_property WIDTHR TYPE INTEGER
set_parameter_property WIDTHR UNITS None
set_parameter_property WIDTHR HDL_PARAMETER true
add_parameter WIDTHK INTEGER 4
set_parameter_property WIDTHK DEFAULT_VALUE 4
set_parameter_property WIDTHK DISPLAY_NAME WIDTHK
set_parameter_property WIDTHK TYPE INTEGER
set_parameter_property WIDTHK UNITS None
set_parameter_property WIDTHK HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges BOTH
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink clock_sreset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 4
add_interface_port slave s_writedata writedata Input 32
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_read read Input 1
add_interface_port slave s_write write Input 1
add_interface_port slave s_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clock
set_interface_property master associatedReset reset_sink
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master m_address address Output 32
add_interface_port master m_readdata readdata Input WIDTH
add_interface_port master m_writedata writedata Output WIDTH
add_interface_port master m_byteenable byteenable Output WIDTHBE
add_interface_port master m_read read Output 1
add_interface_port master m_write write Output 1
add_interface_port master m_waitrequest waitrequest Input 1

