# TCL File Generated by Component Editor 18.1
# Tue May 12 12:51:47 NZST 2020
# DO NOT MODIFY


# 
# vga_output "vga_output" v1.0
#  2020.05.12.12:51:47
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_output
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_output
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CustomIP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_output
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_output
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_output.sv SYSTEM_VERILOG PATH vga_output.sv TOP_LEVEL_FILE
add_fileset_file clock_cross_enable.sv SYSTEM_VERILOG PATH clock_cross_enable.sv


# 
# parameters
# 
add_parameter WIDTH INTEGER 16
set_parameter_property WIDTH DEFAULT_VALUE 16
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 512
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 512
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter VGA_XRES INTEGER 640
set_parameter_property VGA_XRES DEFAULT_VALUE 640
set_parameter_property VGA_XRES DISPLAY_NAME VGA_XRES
set_parameter_property VGA_XRES TYPE INTEGER
set_parameter_property VGA_XRES UNITS None
set_parameter_property VGA_XRES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_XRES HDL_PARAMETER true
add_parameter VGA_HSYNC INTEGER 96
set_parameter_property VGA_HSYNC DEFAULT_VALUE 96
set_parameter_property VGA_HSYNC DISPLAY_NAME VGA_HSYNC
set_parameter_property VGA_HSYNC TYPE INTEGER
set_parameter_property VGA_HSYNC UNITS None
set_parameter_property VGA_HSYNC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_HSYNC HDL_PARAMETER true
add_parameter VGA_HFPORCH INTEGER 16
set_parameter_property VGA_HFPORCH DEFAULT_VALUE 16
set_parameter_property VGA_HFPORCH DISPLAY_NAME VGA_HFPORCH
set_parameter_property VGA_HFPORCH TYPE INTEGER
set_parameter_property VGA_HFPORCH UNITS None
set_parameter_property VGA_HFPORCH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_HFPORCH HDL_PARAMETER true
add_parameter VGA_HBPORCH INTEGER 48
set_parameter_property VGA_HBPORCH DEFAULT_VALUE 48
set_parameter_property VGA_HBPORCH DISPLAY_NAME VGA_HBPORCH
set_parameter_property VGA_HBPORCH TYPE INTEGER
set_parameter_property VGA_HBPORCH UNITS None
set_parameter_property VGA_HBPORCH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_HBPORCH HDL_PARAMETER true
add_parameter VGA_YRES INTEGER 480
set_parameter_property VGA_YRES DEFAULT_VALUE 480
set_parameter_property VGA_YRES DISPLAY_NAME VGA_YRES
set_parameter_property VGA_YRES TYPE INTEGER
set_parameter_property VGA_YRES UNITS None
set_parameter_property VGA_YRES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_YRES HDL_PARAMETER true
add_parameter VGA_VSYNC INTEGER 2
set_parameter_property VGA_VSYNC DEFAULT_VALUE 2
set_parameter_property VGA_VSYNC DISPLAY_NAME VGA_VSYNC
set_parameter_property VGA_VSYNC TYPE INTEGER
set_parameter_property VGA_VSYNC UNITS None
set_parameter_property VGA_VSYNC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_VSYNC HDL_PARAMETER true
add_parameter VGA_VFPORCH INTEGER 10
set_parameter_property VGA_VFPORCH DEFAULT_VALUE 10
set_parameter_property VGA_VFPORCH DISPLAY_NAME VGA_VFPORCH
set_parameter_property VGA_VFPORCH TYPE INTEGER
set_parameter_property VGA_VFPORCH UNITS None
set_parameter_property VGA_VFPORCH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_VFPORCH HDL_PARAMETER true
add_parameter VGA_VBPORCH INTEGER 33
set_parameter_property VGA_VBPORCH DEFAULT_VALUE 33
set_parameter_property VGA_VBPORCH DISPLAY_NAME VGA_VBPORCH
set_parameter_property VGA_VBPORCH TYPE INTEGER
set_parameter_property VGA_VBPORCH UNITS None
set_parameter_property VGA_VBPORCH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_VBPORCH HDL_PARAMETER true
add_parameter NO_SIGNAL_RGB STD_LOGIC_VECTOR 65280
set_parameter_property NO_SIGNAL_RGB DEFAULT_VALUE 65280
set_parameter_property NO_SIGNAL_RGB DISPLAY_NAME NO_SIGNAL_RGB
set_parameter_property NO_SIGNAL_RGB TYPE STD_LOGIC_VECTOR
set_parameter_property NO_SIGNAL_RGB UNITS None
set_parameter_property NO_SIGNAL_RGB ALLOWED_RANGES 0:262143
set_parameter_property NO_SIGNAL_RGB HDL_PARAMETER true


# 
# display items
# 


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock
set_interface_property sink associatedReset clock_sreset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 1
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink st_ready ready Output 1
add_interface_port sink st_valid valid Input 1
add_interface_port sink st_sop startofpacket Input 1
add_interface_port sink st_eop endofpacket Input 1
add_interface_port sink st_data data Input WIDTH


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock vga_clock
set_interface_property vga associatedReset vga_clock_sreset
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga vga_rgb rgb Output WIDTH
add_interface_port vga vga_valid valid Output 1
add_interface_port vga vga_vsync vsync Output 1
add_interface_port vga vga_hsync hsync Output 1


# 
# connection point clock_sreset
# 
add_interface clock_sreset reset end
set_interface_property clock_sreset associatedClock clock
set_interface_property clock_sreset synchronousEdges BOTH
set_interface_property clock_sreset ENABLED true
set_interface_property clock_sreset EXPORT_OF ""
set_interface_property clock_sreset PORT_NAME_MAP ""
set_interface_property clock_sreset CMSIS_SVD_VARIABLES ""
set_interface_property clock_sreset SVD_ADDRESS_GROUP ""

add_interface_port clock_sreset clock_sreset reset Input 1


# 
# connection point vga_clock
# 
add_interface vga_clock clock end
set_interface_property vga_clock clockRate 0
set_interface_property vga_clock ENABLED true
set_interface_property vga_clock EXPORT_OF ""
set_interface_property vga_clock PORT_NAME_MAP ""
set_interface_property vga_clock CMSIS_SVD_VARIABLES ""
set_interface_property vga_clock SVD_ADDRESS_GROUP ""

add_interface_port vga_clock vga_clock clk Input 1


# 
# connection point vga_clock_sreset
# 
add_interface vga_clock_sreset reset end
set_interface_property vga_clock_sreset associatedClock vga_clock
set_interface_property vga_clock_sreset synchronousEdges BOTH
set_interface_property vga_clock_sreset ENABLED true
set_interface_property vga_clock_sreset EXPORT_OF ""
set_interface_property vga_clock_sreset PORT_NAME_MAP ""
set_interface_property vga_clock_sreset CMSIS_SVD_VARIABLES ""
set_interface_property vga_clock_sreset SVD_ADDRESS_GROUP ""

add_interface_port vga_clock_sreset vga_clock_sreset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset clock_sreset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 4
add_interface_port slave s_writedata writedata Input 32
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_read read Input 1
add_interface_port slave s_write write Input 1
add_interface_port slave s_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0

