# TCL File Generated by Component Editor 18.1
# Tue May 12 09:34:55 NZST 2020
# DO NOT MODIFY


# 
# vga_test_pattern "vga_test_pattern" v1.0
#  2020.05.12.09:34:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_test_pattern
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_test_pattern
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CustomIP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_test_pattern
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_test_pattern
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_test_pattern.sv SYSTEM_VERILOG PATH vga_test_pattern.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter XRES INTEGER 640
set_parameter_property XRES DEFAULT_VALUE 640
set_parameter_property XRES DISPLAY_NAME XRES
set_parameter_property XRES TYPE INTEGER
set_parameter_property XRES UNITS None
set_parameter_property XRES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XRES HDL_PARAMETER true
add_parameter YRES INTEGER 480
set_parameter_property YRES DEFAULT_VALUE 480
set_parameter_property YRES DISPLAY_NAME YRES
set_parameter_property YRES TYPE INTEGER
set_parameter_property YRES UNITS None
set_parameter_property YRES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property YRES HDL_PARAMETER true
add_parameter WIDTHR INTEGER 5
set_parameter_property WIDTHR DEFAULT_VALUE 5
set_parameter_property WIDTHR DISPLAY_NAME WIDTHR
set_parameter_property WIDTHR TYPE INTEGER
set_parameter_property WIDTHR UNITS None
set_parameter_property WIDTHR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTHR HDL_PARAMETER true
add_parameter WIDTHG INTEGER 6
set_parameter_property WIDTHG DEFAULT_VALUE 6
set_parameter_property WIDTHG DISPLAY_NAME WIDTHG
set_parameter_property WIDTHG TYPE INTEGER
set_parameter_property WIDTHG UNITS None
set_parameter_property WIDTHG ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTHG HDL_PARAMETER true
add_parameter WIDTHB INTEGER 5
set_parameter_property WIDTHB DEFAULT_VALUE 5
set_parameter_property WIDTHB DISPLAY_NAME WIDTHB
set_parameter_property WIDTHB TYPE INTEGER
set_parameter_property WIDTHB UNITS None
set_parameter_property WIDTHB ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTHB HDL_PARAMETER true
add_parameter WIDTH INTEGER 16
set_parameter_property WIDTH DEFAULT_VALUE 16
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink clock_sreset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock_sink
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 4
add_interface_port slave s_writedata writedata Input 32
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_read read Input 1
add_interface_port slave s_write write Input 1
add_interface_port slave s_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock_sink
set_interface_property source associatedReset reset_sink
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 1
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source st_ready ready Input 1
add_interface_port source st_valid valid Output 1
add_interface_port source st_sop startofpacket Output 1
add_interface_port source st_eop endofpacket Output 1
add_interface_port source st_data data Output WIDTH

